name: Bug Report
description: Report an issue with the Postman platform. 
title: "<title>"
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the issue you encountered. [Github Issue Tracker](https://github.com/postmanlabs/postman-app-support/issues)
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Describe the Issue
    description: |
      A high-level summary or description of the problem that you're facing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: A list of steps that can be followed to recreate the issue.
    placeholder: |
      1. Open a new request tab
      2. Select the Body tab
      3. Select the `raw` type 
      4. See error message...
  validations:
    required: true
- type: textarea
  attributes:
    label: Screenshots or Videos
    description: | 
      Please add screenshots or a short video to help visually explain the problem.
      Ensure that the screenshots/videos do not contain any sensitive information such as API keys or Access Tokens. 
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment Information
    description: |
      examples:
        - **Operating System**: Ubuntu 20.04
        - **Platform Type**: Native App / Postman Web
        - **Postman Version**: 8.8.0
    value: |
        - Operating System: 
        - Platform Type: 
        - Postman Version: 
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional Context?
    description: |
      Please add any other contextual information about the problem, that might be relevant and help explain the issue you're facing.
      You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
